import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#050816',
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 32,
  },
  header: {
    backgroundColor: '#0B1022',
    borderWidth: 1,
    borderColor: '#1A2750',
    borderRadius: 24,
    padding: 18,
    shadowColor: '#00FFA3',
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  headerTexto: {
    gap: 6,
  },
  boasVindas: {
    color: '#7B8DBA',
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.1,
  },
  titulo: {
    color: '#F5F7FF',
    fontSize: 28,
    fontWeight: '800',
  },
  subtitulo: {
    color: '#A8B2D1',
    fontSize: 14,
    lineHeight: 21,
  },
  statusBox: {
    marginTop: 16,
    backgroundColor: '#09101F',
    borderWidth: 1,
    borderColor: '#20346A',
    borderRadius: 18,
    padding: 14,
  },
  statusRotulo: {
    color: '#7FFFD4',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statusValor: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
    marginTop: 6,
  },
  resumoContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  resumoCard: {
    flex: 1,
    minHeight: 92,
    backgroundColor: '#0B1022',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#18264B',
    padding: 14,
    justifyContent: 'space-between',
  },
  resumoValor: {
    color: '#7FFFD4',
    fontSize: 24,
    fontWeight: '800',
  },
  resumoLabel: {
    color: '#A8B2D1',
    fontSize: 12,
    fontWeight: '500',
    marginTop: 8,
    lineHeight: 17,
  },
  secao: {
    marginTop: 20,
  },
  secaoCabecalho: {
    marginBottom: 12,
  },
  secaoTitulo: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  secaoTextoAuxiliar: {
    color: '#8A96B8',
    fontSize: 13,
    marginTop: 4,
    lineHeight: 18,
  },
  gridAcoes: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
  },
  acaoCard: {
    width: '48%',
    backgroundColor: '#0B1022',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#17315F',
    padding: 14,
    minHeight: 150,
  },
  acaoIcone: {
    fontSize: 26,
    marginBottom: 12,
  },
  acaoTitulo: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  acaoDescricao: {
    color: '#9DABC8',
    fontSize: 12,
    lineHeight: 17,
    marginTop: 8,
  },
  dicaCard: {
    backgroundColor: '#09101F',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#20406A',
    padding: 16,
  },
  dicaTexto: {
    color: '#DCE3F7',
    fontSize: 14,
    lineHeight: 22,
  },
  dicaAcoes: {
    marginTop: 14,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  botaoDica: {
    backgroundColor: '#00D084',
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
  },
  botaoDicaTexto: {
    color: '#04111A',
    fontSize: 13,
    fontWeight: '800',
  },
  botaoDicaSecundario: {
    backgroundColor: '#0B1022',
    paddingHorizontal: 16,
    paddingVertical: 11,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#234579',
  },
  botaoDicaSecundarioTexto: {
    color: '#7FFFD4',
    fontSize: 13,
    fontWeight: '800',
  },
  listaNotificacoes: {
    gap: 10,
  },
  cardNotificacao: {
    backgroundColor: '#0B1022',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#18264B',
    padding: 14,
  },
  notificacaoHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pontoDestaque: {
    width: 10,
    height: 10,
    borderRadius: 999,
    backgroundColor: '#7FFFD4',
  },
  notificacaoTitulo: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  notificacaoTag: {
    color: '#7B8DBA',
    fontSize: 11,
    fontWeight: '700',
  },
  notificacaoDescricao: {
    color: '#AAB5D4',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 10,
  },
  cardVazio: {
    backgroundColor: '#0B1022',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#18264B',
    padding: 16,
  },
  cardVazioTitulo: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  cardVazioTexto: {
    color: '#9DABC8',
    fontSize: 13,
    lineHeight: 19,
    marginTop: 8,
  },
  listaRotas: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  roteiroCard: {
    backgroundColor: '#0B1022',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#234579',
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  roteiroTexto: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
});

export default styles;