import { StyleSheet } from 'react-native';

const cores = {
  fundo: '#09111f',
  superficie: '#101a2d',
  superficie2: '#16223a',
  borda: '#243451',
  texto: '#ecf3ff',
  textoSecundario: '#9ab0cf',
  destaque: '#7c3aed',
  sucesso: '#22c55e',
  aviso: '#f59e0b',
};

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: cores.fundo },
  content: { padding: 20, paddingBottom: 40 },
  cabecalho: { marginBottom: 18 },
  titulo: { color: cores.texto, fontSize: 28, fontWeight: '800', marginBottom: 8 },
  subtitulo: { color: cores.textoSecundario, fontSize: 14, lineHeight: 21 },
  resumo: { flexDirection: 'row', gap: 12, marginBottom: 16 },
  resumoCard: {
    flex: 1,
    backgroundColor: cores.superficie,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: cores.borda,
    padding: 14,
  },
  resumoValor: { color: cores.texto, fontSize: 22, fontWeight: '800', marginBottom: 4 },
  resumoTexto: { color: cores.textoSecundario, fontSize: 12 },
  bloco: {
    backgroundColor: cores.superficie,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: cores.borda,
    padding: 16,
    marginBottom: 14,
  },
  blocoTitulo: { color: cores.texto, fontSize: 16, fontWeight: '700', marginBottom: 12 },
  card: {
    backgroundColor: cores.superficie2,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#283a5a',
    padding: 14,
    marginBottom: 10,
  },
  cardTopo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 8,
  },
  cardTitulo: { flex: 1, color: cores.texto, fontSize: 15, fontWeight: '700' },
  status: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  statusNova: {
    backgroundColor: `${cores.aviso}22`,
    borderWidth: 1,
    borderColor: cores.aviso,
  },
  statusLida: {
    backgroundColor: `${cores.sucesso}22`,
    borderWidth: 1,
    borderColor: cores.sucesso,
  },
  statusTexto: { color: cores.texto, fontSize: 11, fontWeight: '700' },
  cardMensagem: { color: '#bfd0ea', fontSize: 13, lineHeight: 19, marginBottom: 8 },
  cardData: { color: cores.textoSecundario, fontSize: 12 },
  estadoVazio: { paddingVertical: 10 },
  estadoVazioTitulo: { color: cores.texto, fontSize: 15, fontWeight: '700', marginBottom: 6 },
  estadoVazioTexto: { color: cores.textoSecundario, fontSize: 13, lineHeight: 19 },
});
